# $DOCKER_USER, $DOCKER_PASS (hide) and $TRAVIS_TOKEN (hide) in Settings > Environment Variables
# Triggering builds (get TOKEN): https://docs.travis-ci.com/user/triggering-builds/

language: bash

sudo: false

env:
  - DOCKERFILE=Dockerfile.ubuntu DOCKERTAG=ubuntu-14.04
  #- DOCKERFILE=Dockerfile.ubuntu-16.04 DOCKERTAG=ubuntu-16.04
  #- DOCKERFILE=Dockerfile.centos DOCKERTAG=centos-7
  #- DOCKERFILE=Dockerfile.debian DOCKERTAG=debian-jessie
  #- DOCKERFILE=Dockerfile.debian-jessie-toollabs DOCKERTAG=debian-jessie-toollabs

services:
  - docker

install:
  - COMMIT=${TRAVIS_COMMIT::8} ;
  - REPO=drtrigon/docker-eagle ;
  - LATEST=ubuntu-14.04 ;
#  - docker login -u $DOCKER_USER -p $DOCKER_PASS ;
#  - docker build -f $DOCKERFILE -t $REPO:$COMMIT . ;
#  - docker tag $REPO:$COMMIT $REPO:$DOCKERTAG ;
#  # - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER ;
#  - if [[ "$DOCKERTAG" == "$LATEST" ]] ; then
#      docker tag $REPO:$COMMIT $REPO:latest ;
#    fi
  - COMMIT=$LATEST ;             # debug: pull instead of build for faster developpment
  - docker pull $REPO:$COMMIT ;  # debug: pull instead of build for faster developpment

script:
  - docker images ;
  - docker run -t -d --name testing $REPO:$DOCKERTAG bin/bash ;
  - docker ps -l ;
  - docker exec -t testing  /bin/bash -c 'xvfb-run -a \$EAGLE -?' ;
  - docker stop testing ;
  - docker rm testing ;
  #- docker rmi $DOCKER:$DOCKERTAG
  #- docker images ;
  #- docker container ls ;
  - docker ps -l ;

  - docker images ;
  - docker run -t --rm $REPO:$COMMIT  /bin/bash -c 'echo xvfb-run -a \$EAGLE -?' || true ;     # DOES need a display
  - docker run -t --rm $REPO:$COMMIT  /bin/bash -c 'xvfb-run -a /opt/eagle-7.7.0/bin/eagle -?' || true ;     # DOES need a display
  - docker run -t --rm $REPO:$COMMIT  /bin/bash -c 'xvfb-run -a \$EAGLE -?' || true ;     # DOES need a display
  - docker run -t --rm $REPO:$COMMIT  "xvfb-run -a \$EAGLE -?" || true ;     # DOES need a display
  - docker run -t --rm $REPO:$COMMIT  xvfb-run -a \$EAGLE -? || true ;     # DOES need a display
  - docker run -t --rm $REPO:$COMMIT  "xvfb-run -a $EAGLE -?" || true ;     # DOES need a display
  - docker run -t --rm $REPO:$COMMIT  /bin/bash -c 'xvfb-run -a \$EAGLE -d?' || true ;    # DOES need a display
  - docker rmi $REPO:$COMMIT
  - docker images ;
  - docker container ls ;
  - docker ps -l ;

#after_success:
#  # Upload to docker if it's on the master branch
#  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
#      docker push $REPO ;
#    fi

#  # trigger docker-sketchbook (same tests based on docker-arduino)
#  - |-
#    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
#      if [[ "$DOCKERTAG" == "$LATEST" ]] ; then
#        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_TOKEN" -d "{\"request\": {\"branch\":\"master\"}}" https://api.travis-ci.org/repo/drtrigon%2Fdocker-file-metadata-wikibot/requests ;
#        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_TOKEN" -d "{\"request\": {\"branch\":\"master\"}}" https://api.travis-ci.org/repo/drtrigon%2Finstall-file-metadata-wikibot/requests ;
#      fi ;
#    fi

notifications:
  email: false
